package backend.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

/**
 * TblApiKey generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblApiKey implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TblApiKeyId id;

	public TblApiKey() {
	}

	public TblApiKey(TblApiKeyId id) {
		this.id = id;
	}

	public TblApiKeyId getId() {
		return this.id;
	}

	public void setId(TblApiKeyId id) {
		this.id = id;
	}

}
