package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblApiKeyId generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblApiKeyId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String key;

	public TblApiKeyId() {
	}

	public TblApiKeyId(int id) {
		this.id = id;
	}

	public TblApiKeyId(int id, String key) {
		this.id = id;
		this.key = key;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblApiKeyId))
			return false;
		TblApiKeyId castOther = (TblApiKeyId) other;

		return (this.getId() == castOther.getId()) && ((this.getKey() == castOther.getKey())
				|| (this.getKey() != null && castOther.getKey() != null && this.getKey().equals(castOther.getKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
		return result;
	}

}
