package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblBillingTypeId generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblBillingTypeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String description;
	private Double energy1;
	private Double energy2;
	private Double energy3;
	private Double energy4;
	private Double energy5;
	private Double energy6;
	private Double energy7;
	private Double energyoffpeak;
	private Double energyonpeak;
	private int id;
	private Double kvarcharge;
	private Double onpeakdemand;
	private Double partialdemand;
	private String peatype;
	private Double service;
	private Double vat;

	public TblBillingTypeId() {
	}

	public TblBillingTypeId(int id) {
		this.id = id;
	}

	public TblBillingTypeId(String description, Double energy1, Double energy2, Double energy3, Double energy4,
			Double energy5, Double energy6, Double energy7, Double energyoffpeak, Double energyonpeak, int id,
			Double kvarcharge, Double onpeakdemand, Double partialdemand, String peatype, Double service, Double vat) {
		this.description = description;
		this.energy1 = energy1;
		this.energy2 = energy2;
		this.energy3 = energy3;
		this.energy4 = energy4;
		this.energy5 = energy5;
		this.energy6 = energy6;
		this.energy7 = energy7;
		this.energyoffpeak = energyoffpeak;
		this.energyonpeak = energyonpeak;
		this.id = id;
		this.kvarcharge = kvarcharge;
		this.onpeakdemand = onpeakdemand;
		this.partialdemand = partialdemand;
		this.peatype = peatype;
		this.service = service;
		this.vat = vat;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getEnergy1() {
		return this.energy1;
	}

	public void setEnergy1(Double energy1) {
		this.energy1 = energy1;
	}

	public Double getEnergy2() {
		return this.energy2;
	}

	public void setEnergy2(Double energy2) {
		this.energy2 = energy2;
	}

	public Double getEnergy3() {
		return this.energy3;
	}

	public void setEnergy3(Double energy3) {
		this.energy3 = energy3;
	}

	public Double getEnergy4() {
		return this.energy4;
	}

	public void setEnergy4(Double energy4) {
		this.energy4 = energy4;
	}

	public Double getEnergy5() {
		return this.energy5;
	}

	public void setEnergy5(Double energy5) {
		this.energy5 = energy5;
	}

	public Double getEnergy6() {
		return this.energy6;
	}

	public void setEnergy6(Double energy6) {
		this.energy6 = energy6;
	}

	public Double getEnergy7() {
		return this.energy7;
	}

	public void setEnergy7(Double energy7) {
		this.energy7 = energy7;
	}

	public Double getEnergyoffpeak() {
		return this.energyoffpeak;
	}

	public void setEnergyoffpeak(Double energyoffpeak) {
		this.energyoffpeak = energyoffpeak;
	}

	public Double getEnergyonpeak() {
		return this.energyonpeak;
	}

	public void setEnergyonpeak(Double energyonpeak) {
		this.energyonpeak = energyonpeak;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Double getKvarcharge() {
		return this.kvarcharge;
	}

	public void setKvarcharge(Double kvarcharge) {
		this.kvarcharge = kvarcharge;
	}

	public Double getOnpeakdemand() {
		return this.onpeakdemand;
	}

	public void setOnpeakdemand(Double onpeakdemand) {
		this.onpeakdemand = onpeakdemand;
	}

	public Double getPartialdemand() {
		return this.partialdemand;
	}

	public void setPartialdemand(Double partialdemand) {
		this.partialdemand = partialdemand;
	}

	public String getPeatype() {
		return this.peatype;
	}

	public void setPeatype(String peatype) {
		this.peatype = peatype;
	}

	public Double getService() {
		return this.service;
	}

	public void setService(Double service) {
		this.service = service;
	}

	public Double getVat() {
		return this.vat;
	}

	public void setVat(Double vat) {
		this.vat = vat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblBillingTypeId))
			return false;
		TblBillingTypeId castOther = (TblBillingTypeId) other;

		return ((this.getDescription() == castOther.getDescription()) || (this.getDescription() != null
				&& castOther.getDescription() != null && this.getDescription().equals(castOther.getDescription())))
				&& ((this.getEnergy1() == castOther.getEnergy1()) || (this.getEnergy1() != null
						&& castOther.getEnergy1() != null && this.getEnergy1().equals(castOther.getEnergy1())))
				&& ((this.getEnergy2() == castOther.getEnergy2()) || (this.getEnergy2() != null
						&& castOther.getEnergy2() != null && this.getEnergy2().equals(castOther.getEnergy2())))
				&& ((this.getEnergy3() == castOther.getEnergy3()) || (this.getEnergy3() != null
						&& castOther.getEnergy3() != null && this.getEnergy3().equals(castOther.getEnergy3())))
				&& ((this.getEnergy4() == castOther.getEnergy4()) || (this.getEnergy4() != null
						&& castOther.getEnergy4() != null && this.getEnergy4().equals(castOther.getEnergy4())))
				&& ((this.getEnergy5() == castOther.getEnergy5()) || (this.getEnergy5() != null
						&& castOther.getEnergy5() != null && this.getEnergy5().equals(castOther.getEnergy5())))
				&& ((this.getEnergy6() == castOther.getEnergy6()) || (this.getEnergy6() != null
						&& castOther.getEnergy6() != null && this.getEnergy6().equals(castOther.getEnergy6())))
				&& ((this.getEnergy7() == castOther.getEnergy7()) || (this.getEnergy7() != null
						&& castOther.getEnergy7() != null && this.getEnergy7().equals(castOther.getEnergy7())))
				&& ((this.getEnergyoffpeak() == castOther.getEnergyoffpeak())
						|| (this.getEnergyoffpeak() != null && castOther.getEnergyoffpeak() != null
								&& this.getEnergyoffpeak().equals(castOther.getEnergyoffpeak())))
				&& ((this.getEnergyonpeak() == castOther.getEnergyonpeak())
						|| (this.getEnergyonpeak() != null && castOther.getEnergyonpeak() != null
								&& this.getEnergyonpeak().equals(castOther.getEnergyonpeak())))
				&& (this.getId() == castOther.getId())
				&& ((this.getKvarcharge() == castOther.getKvarcharge()) || (this.getKvarcharge() != null
						&& castOther.getKvarcharge() != null && this.getKvarcharge().equals(castOther.getKvarcharge())))
				&& ((this.getOnpeakdemand() == castOther.getOnpeakdemand())
						|| (this.getOnpeakdemand() != null && castOther.getOnpeakdemand() != null
								&& this.getOnpeakdemand().equals(castOther.getOnpeakdemand())))
				&& ((this.getPartialdemand() == castOther.getPartialdemand())
						|| (this.getPartialdemand() != null && castOther.getPartialdemand() != null
								&& this.getPartialdemand().equals(castOther.getPartialdemand())))
				&& ((this.getPeatype() == castOther.getPeatype()) || (this.getPeatype() != null
						&& castOther.getPeatype() != null && this.getPeatype().equals(castOther.getPeatype())))
				&& ((this.getService() == castOther.getService()) || (this.getService() != null
						&& castOther.getService() != null && this.getService().equals(castOther.getService())))
				&& ((this.getVat() == castOther.getVat()) || (this.getVat() != null && castOther.getVat() != null
						&& this.getVat().equals(castOther.getVat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getEnergy1() == null ? 0 : this.getEnergy1().hashCode());
		result = 37 * result + (getEnergy2() == null ? 0 : this.getEnergy2().hashCode());
		result = 37 * result + (getEnergy3() == null ? 0 : this.getEnergy3().hashCode());
		result = 37 * result + (getEnergy4() == null ? 0 : this.getEnergy4().hashCode());
		result = 37 * result + (getEnergy5() == null ? 0 : this.getEnergy5().hashCode());
		result = 37 * result + (getEnergy6() == null ? 0 : this.getEnergy6().hashCode());
		result = 37 * result + (getEnergy7() == null ? 0 : this.getEnergy7().hashCode());
		result = 37 * result + (getEnergyoffpeak() == null ? 0 : this.getEnergyoffpeak().hashCode());
		result = 37 * result + (getEnergyonpeak() == null ? 0 : this.getEnergyonpeak().hashCode());
		result = 37 * result + this.getId();
		result = 37 * result + (getKvarcharge() == null ? 0 : this.getKvarcharge().hashCode());
		result = 37 * result + (getOnpeakdemand() == null ? 0 : this.getOnpeakdemand().hashCode());
		result = 37 * result + (getPartialdemand() == null ? 0 : this.getPartialdemand().hashCode());
		result = 37 * result + (getPeatype() == null ? 0 : this.getPeatype().hashCode());
		result = 37 * result + (getService() == null ? 0 : this.getService().hashCode());
		result = 37 * result + (getVat() == null ? 0 : this.getVat().hashCode());
		return result;
	}

}
