package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblEnergyId generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblEnergyId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Double consumption;
	private Double export;
	private int id;
	private Integer idSite;
	private Double import_;
	private Double production;
	private Double selfconsumption;
	private Timestamp time;

	public TblEnergyId() {
	}

	public TblEnergyId(int id) {
		this.id = id;
	}

	public TblEnergyId(Double consumption, Double export, int id, Integer idSite, Double import_, Double production,
			Double selfconsumption, Timestamp time) {
		this.consumption = consumption;
		this.export = export;
		this.id = id;
		this.idSite = idSite;
		this.import_ = import_;
		this.production = production;
		this.selfconsumption = selfconsumption;
		this.time = time;
	}

	public Double getConsumption() {
		return this.consumption;
	}

	public void setConsumption(Double consumption) {
		this.consumption = consumption;
	}

	public Double getExport() {
		return this.export;
	}

	public void setExport(Double export) {
		this.export = export;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getIdSite() {
		return this.idSite;
	}

	public void setIdSite(Integer idSite) {
		this.idSite = idSite;
	}

	public Double getImport_() {
		return this.import_;
	}

	public void setImport_(Double import_) {
		this.import_ = import_;
	}

	public Double getProduction() {
		return this.production;
	}

	public void setProduction(Double production) {
		this.production = production;
	}

	public Double getSelfconsumption() {
		return this.selfconsumption;
	}

	public void setSelfconsumption(Double selfconsumption) {
		this.selfconsumption = selfconsumption;
	}

	public Timestamp getTime() {
		return this.time;
	}

	public void setTime(Timestamp time) {
		this.time = time;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblEnergyId))
			return false;
		TblEnergyId castOther = (TblEnergyId) other;

		return ((this.getConsumption() == castOther.getConsumption()) || (this.getConsumption() != null
				&& castOther.getConsumption() != null && this.getConsumption().equals(castOther.getConsumption())))
				&& ((this.getExport() == castOther.getExport()) || (this.getExport() != null
						&& castOther.getExport() != null && this.getExport().equals(castOther.getExport())))
				&& (this.getId() == castOther.getId())
				&& ((this.getIdSite() == castOther.getIdSite()) || (this.getIdSite() != null
						&& castOther.getIdSite() != null && this.getIdSite().equals(castOther.getIdSite())))
				&& ((this.getImport_() == castOther.getImport_()) || (this.getImport_() != null
						&& castOther.getImport_() != null && this.getImport_().equals(castOther.getImport_())))
				&& ((this.getProduction() == castOther.getProduction()) || (this.getProduction() != null
						&& castOther.getProduction() != null && this.getProduction().equals(castOther.getProduction())))
				&& ((this.getSelfconsumption() == castOther.getSelfconsumption())
						|| (this.getSelfconsumption() != null && castOther.getSelfconsumption() != null
								&& this.getSelfconsumption().equals(castOther.getSelfconsumption())))
				&& ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null
						&& this.getTime().equals(castOther.getTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getConsumption() == null ? 0 : this.getConsumption().hashCode());
		result = 37 * result + (getExport() == null ? 0 : this.getExport().hashCode());
		result = 37 * result + this.getId();
		result = 37 * result + (getIdSite() == null ? 0 : this.getIdSite().hashCode());
		result = 37 * result + (getImport_() == null ? 0 : this.getImport_().hashCode());
		result = 37 * result + (getProduction() == null ? 0 : this.getProduction().hashCode());
		result = 37 * result + (getSelfconsumption() == null ? 0 : this.getSelfconsumption().hashCode());
		result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
		return result;
	}

}
