package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblEnergy generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblEnergy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TblEnergyId id;

	public TblEnergy() {
	}

	public TblEnergy(TblEnergyId id) {
		this.id = id;
	}

	public TblEnergyId getId() {
		return this.id;
	}

	public void setId(TblEnergyId id) {
		this.id = id;
	}

}
