package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblEnergyMonitor generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblEnergyMonitor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TblEnergyMonitorId id;

	public TblEnergyMonitor() {
	}

	public TblEnergyMonitor(TblEnergyMonitorId id) {
		this.id = id;
	}

	public TblEnergyMonitorId getId() {
		return this.id;
	}

	public void setId(TblEnergyMonitorId id) {
		this.id = id;
	}

}
