package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblEnergyMonitorId generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblEnergyMonitorId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Timestamp beginTime;
	private Timestamp finalTime;
	private int id;
	private Integer idSite;
	private Double kvardemand;
	private Double kwdemand;
	private Double kwhCons;
	private Integer tod;
	private Integer tou;

	public TblEnergyMonitorId() {
	}

	public TblEnergyMonitorId(int id) {
		this.id = id;
	}

	public TblEnergyMonitorId(Timestamp beginTime, Timestamp finalTime, int id, Integer idSite, Double kvardemand,
			Double kwdemand, Double kwhCons, Integer tod, Integer tou) {
		this.beginTime = beginTime;
		this.finalTime = finalTime;
		this.id = id;
		this.idSite = idSite;
		this.kvardemand = kvardemand;
		this.kwdemand = kwdemand;
		this.kwhCons = kwhCons;
		this.tod = tod;
		this.tou = tou;
	}

	public Timestamp getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Timestamp beginTime) {
		this.beginTime = beginTime;
	}

	public Timestamp getFinalTime() {
		return this.finalTime;
	}

	public void setFinalTime(Timestamp finalTime) {
		this.finalTime = finalTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getIdSite() {
		return this.idSite;
	}

	public void setIdSite(Integer idSite) {
		this.idSite = idSite;
	}

	public Double getKvardemand() {
		return this.kvardemand;
	}

	public void setKvardemand(Double kvardemand) {
		this.kvardemand = kvardemand;
	}

	public Double getKwdemand() {
		return this.kwdemand;
	}

	public void setKwdemand(Double kwdemand) {
		this.kwdemand = kwdemand;
	}

	public Double getKwhCons() {
		return this.kwhCons;
	}

	public void setKwhCons(Double kwhCons) {
		this.kwhCons = kwhCons;
	}

	public Integer getTod() {
		return this.tod;
	}

	public void setTod(Integer tod) {
		this.tod = tod;
	}

	public Integer getTou() {
		return this.tou;
	}

	public void setTou(Integer tou) {
		this.tou = tou;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblEnergyMonitorId))
			return false;
		TblEnergyMonitorId castOther = (TblEnergyMonitorId) other;

		return ((this.getBeginTime() == castOther.getBeginTime()) || (this.getBeginTime() != null
				&& castOther.getBeginTime() != null && this.getBeginTime().equals(castOther.getBeginTime())))
				&& ((this.getFinalTime() == castOther.getFinalTime()) || (this.getFinalTime() != null
						&& castOther.getFinalTime() != null && this.getFinalTime().equals(castOther.getFinalTime())))
				&& (this.getId() == castOther.getId())
				&& ((this.getIdSite() == castOther.getIdSite()) || (this.getIdSite() != null
						&& castOther.getIdSite() != null && this.getIdSite().equals(castOther.getIdSite())))
				&& ((this.getKvardemand() == castOther.getKvardemand()) || (this.getKvardemand() != null
						&& castOther.getKvardemand() != null && this.getKvardemand().equals(castOther.getKvardemand())))
				&& ((this.getKwdemand() == castOther.getKwdemand()) || (this.getKwdemand() != null
						&& castOther.getKwdemand() != null && this.getKwdemand().equals(castOther.getKwdemand())))
				&& ((this.getKwhCons() == castOther.getKwhCons()) || (this.getKwhCons() != null
						&& castOther.getKwhCons() != null && this.getKwhCons().equals(castOther.getKwhCons())))
				&& ((this.getTod() == castOther.getTod()) || (this.getTod() != null && castOther.getTod() != null
						&& this.getTod().equals(castOther.getTod())))
				&& ((this.getTou() == castOther.getTou()) || (this.getTou() != null && castOther.getTou() != null
						&& this.getTou().equals(castOther.getTou())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBeginTime() == null ? 0 : this.getBeginTime().hashCode());
		result = 37 * result + (getFinalTime() == null ? 0 : this.getFinalTime().hashCode());
		result = 37 * result + this.getId();
		result = 37 * result + (getIdSite() == null ? 0 : this.getIdSite().hashCode());
		result = 37 * result + (getKvardemand() == null ? 0 : this.getKvardemand().hashCode());
		result = 37 * result + (getKwdemand() == null ? 0 : this.getKwdemand().hashCode());
		result = 37 * result + (getKwhCons() == null ? 0 : this.getKwhCons().hashCode());
		result = 37 * result + (getTod() == null ? 0 : this.getTod().hashCode());
		result = 37 * result + (getTou() == null ? 0 : this.getTou().hashCode());
		return result;
	}

}
