package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import java.sql.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblFtId generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblFtId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Double rate;
	private Date time;

	public TblFtId() {
	}

	public TblFtId(int id) {
		this.id = id;
	}

	public TblFtId(int id, Double rate, Date time) {
		this.id = id;
		this.rate = rate;
		this.time = time;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblFtId))
			return false;
		TblFtId castOther = (TblFtId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getRate() == castOther.getRate()) || (this.getRate() != null && castOther.getRate() != null
						&& this.getRate().equals(castOther.getRate())))
				&& ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null
						&& this.getTime().equals(castOther.getTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getRate() == null ? 0 : this.getRate().hashCode());
		result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
		return result;
	}

}
