package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblFt generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblFt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TblFtId id;

	public TblFt() {
	}

	public TblFt(TblFtId id) {
		this.id = id;
	}

	public TblFtId getId() {
		return this.id;
	}

	public void setId(TblFtId id) {
		this.id = id;
	}

}
