package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import java.sql.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblHolidayId generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblHolidayId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Date holidayDate;
	private String holidayDesc;
	private int id;

	public TblHolidayId() {
	}

	public TblHolidayId(int id) {
		this.id = id;
	}

	public TblHolidayId(Date holidayDate, String holidayDesc, int id) {
		this.holidayDate = holidayDate;
		this.holidayDesc = holidayDesc;
		this.id = id;
	}

	public Date getHolidayDate() {
		return this.holidayDate;
	}

	public void setHolidayDate(Date holidayDate) {
		this.holidayDate = holidayDate;
	}

	public String getHolidayDesc() {
		return this.holidayDesc;
	}

	public void setHolidayDesc(String holidayDesc) {
		this.holidayDesc = holidayDesc;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblHolidayId))
			return false;
		TblHolidayId castOther = (TblHolidayId) other;

		return ((this.getHolidayDate() == castOther.getHolidayDate()) || (this.getHolidayDate() != null
				&& castOther.getHolidayDate() != null && this.getHolidayDate().equals(castOther.getHolidayDate())))
				&& ((this.getHolidayDesc() == castOther.getHolidayDesc())
						|| (this.getHolidayDesc() != null && castOther.getHolidayDesc() != null
								&& this.getHolidayDesc().equals(castOther.getHolidayDesc())))
				&& (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHolidayDate() == null ? 0 : this.getHolidayDate().hashCode());
		result = 37 * result + (getHolidayDesc() == null ? 0 : this.getHolidayDesc().hashCode());
		result = 37 * result + this.getId();
		return result;
	}

}
