package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblPower generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblPower implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TblPowerId id;

	public TblPower() {
	}

	public TblPower(TblPowerId id) {
		this.id = id;
	}

	public TblPowerId getId() {
		return this.id;
	}

	public void setId(TblPowerId id) {
		this.id = id;
	}

}
