package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblPowerId generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblPowerId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Integer idSite;
	private Double kwCons;
	private Double kwFeedin;
	private Double kwProduction;
	private Double kwPurchesed;
	private Double kwSelfcons;
	private Timestamp time;

	public TblPowerId() {
	}

	public TblPowerId(int id) {
		this.id = id;
	}

	public TblPowerId(int id, Integer idSite, Double kwCons, Double kwFeedin, Double kwProduction, Double kwPurchesed,
			Double kwSelfcons, Timestamp time) {
		this.id = id;
		this.idSite = idSite;
		this.kwCons = kwCons;
		this.kwFeedin = kwFeedin;
		this.kwProduction = kwProduction;
		this.kwPurchesed = kwPurchesed;
		this.kwSelfcons = kwSelfcons;
		this.time = time;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getIdSite() {
		return this.idSite;
	}

	public void setIdSite(Integer idSite) {
		this.idSite = idSite;
	}

	public Double getKwCons() {
		return this.kwCons;
	}

	public void setKwCons(Double kwCons) {
		this.kwCons = kwCons;
	}

	public Double getKwFeedin() {
		return this.kwFeedin;
	}

	public void setKwFeedin(Double kwFeedin) {
		this.kwFeedin = kwFeedin;
	}

	public Double getKwProduction() {
		return this.kwProduction;
	}

	public void setKwProduction(Double kwProduction) {
		this.kwProduction = kwProduction;
	}

	public Double getKwPurchesed() {
		return this.kwPurchesed;
	}

	public void setKwPurchesed(Double kwPurchesed) {
		this.kwPurchesed = kwPurchesed;
	}

	public Double getKwSelfcons() {
		return this.kwSelfcons;
	}

	public void setKwSelfcons(Double kwSelfcons) {
		this.kwSelfcons = kwSelfcons;
	}

	public Timestamp getTime() {
		return this.time;
	}

	public void setTime(Timestamp time) {
		this.time = time;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblPowerId))
			return false;
		TblPowerId castOther = (TblPowerId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getIdSite() == castOther.getIdSite()) || (this.getIdSite() != null
						&& castOther.getIdSite() != null && this.getIdSite().equals(castOther.getIdSite())))
				&& ((this.getKwCons() == castOther.getKwCons()) || (this.getKwCons() != null
						&& castOther.getKwCons() != null && this.getKwCons().equals(castOther.getKwCons())))
				&& ((this.getKwFeedin() == castOther.getKwFeedin()) || (this.getKwFeedin() != null
						&& castOther.getKwFeedin() != null && this.getKwFeedin().equals(castOther.getKwFeedin())))
				&& ((this.getKwProduction() == castOther.getKwProduction())
						|| (this.getKwProduction() != null && castOther.getKwProduction() != null
								&& this.getKwProduction().equals(castOther.getKwProduction())))
				&& ((this.getKwPurchesed() == castOther.getKwPurchesed())
						|| (this.getKwPurchesed() != null && castOther.getKwPurchesed() != null
								&& this.getKwPurchesed().equals(castOther.getKwPurchesed())))
				&& ((this.getKwSelfcons() == castOther.getKwSelfcons()) || (this.getKwSelfcons() != null
						&& castOther.getKwSelfcons() != null && this.getKwSelfcons().equals(castOther.getKwSelfcons())))
				&& ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null
						&& this.getTime().equals(castOther.getTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getIdSite() == null ? 0 : this.getIdSite().hashCode());
		result = 37 * result + (getKwCons() == null ? 0 : this.getKwCons().hashCode());
		result = 37 * result + (getKwFeedin() == null ? 0 : this.getKwFeedin().hashCode());
		result = 37 * result + (getKwProduction() == null ? 0 : this.getKwProduction().hashCode());
		result = 37 * result + (getKwPurchesed() == null ? 0 : this.getKwPurchesed().hashCode());
		result = 37 * result + (getKwSelfcons() == null ? 0 : this.getKwSelfcons().hashCode());
		result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
		return result;
	}

}
