package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblSiteId generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblSiteId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String address;
	private int id;
	private Integer idSite;
	private String installed;
	private String location;
	private String peakpower;
	private String sitename;
	private String status;
	private String updated;

	public TblSiteId() {
	}

	public TblSiteId(int id) {
		this.id = id;
	}

	public TblSiteId(String address, int id, Integer idSite, String installed, String location, String peakpower,
			String sitename, String status, String updated) {
		this.address = address;
		this.id = id;
		this.idSite = idSite;
		this.installed = installed;
		this.location = location;
		this.peakpower = peakpower;
		this.sitename = sitename;
		this.status = status;
		this.updated = updated;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getIdSite() {
		return this.idSite;
	}

	public void setIdSite(Integer idSite) {
		this.idSite = idSite;
	}

	public String getInstalled() {
		return this.installed;
	}

	public void setInstalled(String installed) {
		this.installed = installed;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getPeakpower() {
		return this.peakpower;
	}

	public void setPeakpower(String peakpower) {
		this.peakpower = peakpower;
	}

	public String getSitename() {
		return this.sitename;
	}

	public void setSitename(String sitename) {
		this.sitename = sitename;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getUpdated() {
		return this.updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblSiteId))
			return false;
		TblSiteId castOther = (TblSiteId) other;

		return ((this.getAddress() == castOther.getAddress()) || (this.getAddress() != null
				&& castOther.getAddress() != null && this.getAddress().equals(castOther.getAddress())))
				&& (this.getId() == castOther.getId())
				&& ((this.getIdSite() == castOther.getIdSite()) || (this.getIdSite() != null
						&& castOther.getIdSite() != null && this.getIdSite().equals(castOther.getIdSite())))
				&& ((this.getInstalled() == castOther.getInstalled()) || (this.getInstalled() != null
						&& castOther.getInstalled() != null && this.getInstalled().equals(castOther.getInstalled())))
				&& ((this.getLocation() == castOther.getLocation()) || (this.getLocation() != null
						&& castOther.getLocation() != null && this.getLocation().equals(castOther.getLocation())))
				&& ((this.getPeakpower() == castOther.getPeakpower()) || (this.getPeakpower() != null
						&& castOther.getPeakpower() != null && this.getPeakpower().equals(castOther.getPeakpower())))
				&& ((this.getSitename() == castOther.getSitename()) || (this.getSitename() != null
						&& castOther.getSitename() != null && this.getSitename().equals(castOther.getSitename())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getUpdated() == castOther.getUpdated()) || (this.getUpdated() != null
						&& castOther.getUpdated() != null && this.getUpdated().equals(castOther.getUpdated())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result + this.getId();
		result = 37 * result + (getIdSite() == null ? 0 : this.getIdSite().hashCode());
		result = 37 * result + (getInstalled() == null ? 0 : this.getInstalled().hashCode());
		result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
		result = 37 * result + (getPeakpower() == null ? 0 : this.getPeakpower().hashCode());
		result = 37 * result + (getSitename() == null ? 0 : this.getSitename().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getUpdated() == null ? 0 : this.getUpdated().hashCode());
		return result;
	}

}
