package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblSite generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblSite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TblSiteId id;

	public TblSite() {
	}

	public TblSite(TblSiteId id) {
		this.id = id;
	}

	public TblSiteId getId() {
		return this.id;
	}

	public void setId(TblSiteId id) {
		this.id = id;
	}

}
