package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblSiteTypeId generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblSiteTypeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Integer idBilingType;
	private Integer idSite;

	public TblSiteTypeId() {
	}

	public TblSiteTypeId(int id) {
		this.id = id;
	}

	public TblSiteTypeId(int id, Integer idBilingType, Integer idSite) {
		this.id = id;
		this.idBilingType = idBilingType;
		this.idSite = idSite;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getIdBilingType() {
		return this.idBilingType;
	}

	public void setIdBilingType(Integer idBilingType) {
		this.idBilingType = idBilingType;
	}

	public Integer getIdSite() {
		return this.idSite;
	}

	public void setIdSite(Integer idSite) {
		this.idSite = idSite;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblSiteTypeId))
			return false;
		TblSiteTypeId castOther = (TblSiteTypeId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getIdBilingType() == castOther.getIdBilingType())
						|| (this.getIdBilingType() != null && castOther.getIdBilingType() != null
								&& this.getIdBilingType().equals(castOther.getIdBilingType())))
				&& ((this.getIdSite() == castOther.getIdSite()) || (this.getIdSite() != null
						&& castOther.getIdSite() != null && this.getIdSite().equals(castOther.getIdSite())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getIdBilingType() == null ? 0 : this.getIdBilingType().hashCode());
		result = 37 * result + (getIdSite() == null ? 0 : this.getIdSite().hashCode());
		return result;
	}

}
