package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblUsersSite generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblUsersSite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TblUsersSiteId id;

	public TblUsersSite() {
	}

	public TblUsersSite(TblUsersSiteId id) {
		this.id = id;
	}

	public TblUsersSiteId getId() {
		return this.id;
	}

	public void setId(TblUsersSiteId id) {
		this.id = id;
	}

}
