package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblUsersGroups generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblUsersGroups implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private int userId;
	private int groupId;

	public TblUsersGroups() {
	}

	public TblUsersGroups(int id, int userId, int groupId) {
		this.id = id;
		this.userId = userId;
		this.groupId = groupId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

}
