package backend.model;
// Generated Apr 24, 2023, 9:30:03 AM by Hibernate Tools 6.1.5.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TblUsersSiteId generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TblUsersSiteId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Integer idSite;
	private Integer idUser;

	public TblUsersSiteId() {
	}

	public TblUsersSiteId(int id) {
		this.id = id;
	}

	public TblUsersSiteId(int id, Integer idSite, Integer idUser) {
		this.id = id;
		this.idSite = idSite;
		this.idUser = idUser;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getIdSite() {
		return this.idSite;
	}

	public void setIdSite(Integer idSite) {
		this.idSite = idSite;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblUsersSiteId))
			return false;
		TblUsersSiteId castOther = (TblUsersSiteId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getIdSite() == castOther.getIdSite()) || (this.getIdSite() != null
						&& castOther.getIdSite() != null && this.getIdSite().equals(castOther.getIdSite())))
				&& ((this.getIdUser() == castOther.getIdUser()) || (this.getIdUser() != null
						&& castOther.getIdUser() != null && this.getIdUser().equals(castOther.getIdUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getIdSite() == null ? 0 : this.getIdSite().hashCode());
		result = 37 * result + (getIdUser() == null ? 0 : this.getIdUser().hashCode());
		return result;
	}

}
